// Public manifest key keeps the unpacked prototype extension ID stable.
export const EXTENSION_KEY =
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzzwzw2UVJOGNeCJI8qdzyaBONCZPGXAlCF4GaiOCmZROR8TzDPPkINuUeeBwkdciRChHVtmcdKYd5JstUH2hBAmynkoCaOAeKbc6akH2Q50qVFQHBca1q9nusHCaV0n5oG6YHRM6n6i5MzkbRTHhDqtuP9+C4tp/xoLFCePkZs/shiZUksDI1INPockJapT6eEi2wQlA0Xppaa7hBk9kcZ+gFNGEE8ap37yNScImyd62Rd19fQrjpByGgPUb8rjuQFyW0vK51rj9tDbk9PZzRsgENAO6kqG7kE3R9+f6WQYePqicWX9gQkaEJfHJ69kE2fZc56E56eHfPckFYnrbVwIDAQAB';
export const EXTENSION_ID = 'cnebjlcejndghnankjfclflijolcnbnn';
